# Generated by Django 2.2 on 2020-08-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('run', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=400)),
                ('profession', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('run', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'institution',
            },
        ),
    ]
