# Generated by Django 2.2 on 2020-08-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'health_plan',
            },
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='run',
        ),
        migrations.AddField(
            model_name='client',
            name='nationality',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='institution',
            name='name_of_legal_representative',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='institution',
            name='rut',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='client',
            name='full_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='profession',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='run',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='institution',
            name='address',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='institution',
            name='business_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
